name: run-data-fetch-test
run-name: fetch-hhs-data
on: [push]
jobs:
  fetch-hhs-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Script
        run: ./src/data_api_fetch_all.sh data

